### ISSUE TITLE
when import: from audit_trail.history import AuditTrail, AuditManager                                                                                                               i get error:         File "/home/tranlam/Documents/helio_web_env/local/lib/python2.7/site-packages/audit_trail/history.py", line 51     def update_or_create(self, *args, defaults=None, **kwargs):                                               SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by huyhoang1996vn** [Dharmik8478/django-model-audit#2]

**Comment by Dharmik8478** [comment]
@huyhoang1996 thanks for using this package. From your error message it looks like you are using it for `python2.*` and this package is built for `python3.*`. And I don't have any plan to make it python2 compatible hence closing this.
You can use https://github.com/ryfloyd/django-model-audit, by looking with commits done on it looks like it is compatible with pyhton2.
